name: BoxityERPv2 System

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v4

            - name: Copy Specific Folders to Server
              run: |
                  sshpass -p 'LibrA21101998' rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
                      ./app ./resources ./routes \
                      boxity@153.92.5.213:/erpv2-custom/samcellular-be/
